export enum HTTP_STATUS_CODES {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  PROXY_SWITCH = 306,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIME_OUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  REQUEST_ENTITY_TOO_LARGE = 413,
  REQUEST_URL_TOO_LARGE = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUEST_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIME_OUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
}

export const HTTP_RESPONSES = [
  {
    code: HTTP_STATUS_CODES.CONTINUE,
    description: 'Continue',
    message: 'Continuar',
  },
  {
    code: HTTP_STATUS_CODES.SWITCHING_PROTOCOLS,
    description: 'Switching Protocols',
    message: 'Mudando Protocolos',
  },
  {
    code: HTTP_STATUS_CODES.PROCESSING,
    description: 'Processing',
    message: 'Processando',
  },
  {
    code: HTTP_STATUS_CODES.OK,
    description: 'Ok',
    message: 'OK',
  },
  {
    code: HTTP_STATUS_CODES.CREATED,
    description: 'Created',
    message: 'Criado',
  },
  {
    code: HTTP_STATUS_CODES.ACCEPTED,
    description: 'Accepted',
    message: 'Aceito',
  },
  {
    code: HTTP_STATUS_CODES.NON_AUTHORITATIVE_INFORMATION,
    description: 'Non-Authoritative Information',
    message: 'Não autorizado',
  },
  {
    code: HTTP_STATUS_CODES.NO_CONTENT,
    description: 'No Content',
    message: 'Nenhum Conteúdo',
  },
  {
    code: HTTP_STATUS_CODES.RESET_CONTENT,
    description: 'Reset Content',
    message: 'Resetar Conteúdo',
  },
  {
    code: HTTP_STATUS_CODES.PARTIAL_CONTENT,
    description: 'Partial Content',
    message: 'Conteúdo Parcial',
  },
  {
    code: HTTP_STATUS_CODES.MULTIPLE_CHOICES,
    description: 'Multiple Choices',
    message: 'Múltipla Escolha',
  },
  {
    code: HTTP_STATUS_CODES.MOVED_PERMANENTLY,
    description: 'Moved Permanently',
    message: 'Movido Permanentemente',
  },
  {
    code: HTTP_STATUS_CODES.FOUND,
    description: 'Found',
    message: 'Encontrado',
  },
  {
    code: HTTP_STATUS_CODES.SEE_OTHER,
    description: 'See Other',
    message: 'Veja outro',
  },
  {
    code: HTTP_STATUS_CODES.NOT_MODIFIED,
    description: 'Not Modified',
    message: 'Não modificado',
  },
  {
    code: HTTP_STATUS_CODES.USE_PROXY,
    description: 'Use Proxy',
    message: 'Use Proxy',
  },
  {
    code: HTTP_STATUS_CODES.PROXY_SWITCH,
    description: 'Proxy Switch',
    message: 'Proxy Trocado',
  },
  {
    code: HTTP_STATUS_CODES.BAD_REQUEST,
    description: 'Bad Request',
    message: 'Solicitação Inválida',
  },
  {
    code: HTTP_STATUS_CODES.UNAUTHORIZED,
    description: 'Unauthorized',
    message: 'Não autorizado',
  },
  {
    code: HTTP_STATUS_CODES.PAYMENT_REQUIRED,
    description: 'Payment Required',
    message: 'Pagamento necessário',
  },
  {
    code: HTTP_STATUS_CODES.FORBIDDEN,
    description: 'Forbidden',
    message: 'Proibido',
  },
  {
    code: HTTP_STATUS_CODES.NOT_FOUND,
    description: 'Not Found',
    message: 'Não encontrado',
  },
  {
    code: HTTP_STATUS_CODES.METHOD_NOT_ALLOWED,
    description: 'Method Not Allowed',
    message: 'Método não permitido',
  },
  {
    code: HTTP_STATUS_CODES.NOT_ACCEPTABLE,
    description: 'Not Acceptable',
    message: 'Não aceito',
  },
  {
    code: HTTP_STATUS_CODES.PROXY_AUTHENTICATION_REQUIRED,
    description: 'Proxy Authentication Required',
    message: 'Autenticação de Proxy Necessária',
  },
  {
    code: HTTP_STATUS_CODES.REQUEST_TIME_OUT,
    description: 'Request Time-out',
    message: 'Tempo de solicitação esgotado',
  },
  {
    code: HTTP_STATUS_CODES.CONFLICT,
    description: 'Conflict',
    message: 'Conflito',
  },
  {
    code: HTTP_STATUS_CODES.GONE,
    description: 'Gone',
    message: 'Perdido',
  },
  {
    code: HTTP_STATUS_CODES.LENGTH_REQUIRED,
    description: 'Length Required',
    message: 'Duração necessária',
  },
  {
    code: HTTP_STATUS_CODES.PRECONDITION_FAILED,
    description: 'Precondition Failed',
    message: 'Falha de pré-condição',
  },
  {
    code: HTTP_STATUS_CODES.REQUEST_ENTITY_TOO_LARGE,
    description: 'Request Entity Too Large',
    message: 'Solicitação da entidade muito extensa',
  },
  {
    code: HTTP_STATUS_CODES.REQUEST_URL_TOO_LARGE,
    description: 'Request-URL Too Large',
    message: 'Solicitação de URL muito Longa',
  },
  {
    code: HTTP_STATUS_CODES.UNSUPPORTED_MEDIA_TYPE,
    description: 'Unsupported Media Type',
    message: 'Tipo de mídia não suportado',
  },
  {
    code: HTTP_STATUS_CODES.REQUEST_RANGE_NOT_SATISFIABLE,
    description: 'Request Range Not Satisfiable',
    message: 'Solicitação de faixa não satisfatória',
  },
  {
    code: HTTP_STATUS_CODES.EXPECTATION_FAILED,
    description: 'Expectation Failed',
    message: 'Falha na expectativa',
  },
  {
    code: HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR,
    description: 'Internal Server Error',
    message: 'Erro do Servidor Interno',
  },
  {
    code: HTTP_STATUS_CODES.NOT_IMPLEMENTED,
    description: 'Not Implemented',
    message: 'Não implementado',
  },
  {
    code: HTTP_STATUS_CODES.BAD_GATEWAY,
    description: 'Bad Gateway',
    message: 'Porta de entrada ruim',
  },
  {
    code: HTTP_STATUS_CODES.SERVICE_UNAVAILABLE,
    description: 'Service Unavailable',
    message: 'Serviço Indisponível',
  },
  {
    code: HTTP_STATUS_CODES.GATEWAY_TIME_OUT,
    description: 'Gateway Time-out',
    message: 'Tempo limite da Porta de Entrada',
  },
  {
    code: HTTP_STATUS_CODES.HTTP_VERSION_NOT_SUPPORTED,
    description: 'HTTP Version Not Supported',
    message: 'Versão HTTP não suportada',
  },
]
